=== DaniDF/ProgettoIngSoftware/build/exploded/ProgettoIngSoftware/db/configDB.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT db (db-instance+)>
<!ELEMENT db-instance (db-url,db-username,db-password)>
<!ELEMENT db-url (#PCDATA)>
<!ELEMENT db-username (#PCDATA)>
<!ELEMENT db-password (#PCDATA)>
<!ATTLIST db-instance type (MYSQL|DB2) #REQUIRED>

=== DaniDF/ProgettoIngSoftware/web/db/configDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE db SYSTEM "configDB.dtd">

<db>
	<db-instance type="MYSQL">
		<db-url>mysql://192.168.85.10:3306?serverTimezone=UTC</db-url>
		<db-username>ProgettoIngSoftware</db-username>
		<db-password>pis</db-password>
	</db-instance>
	
	<db-instance type="DB2">
		<db-url>db2://diva.deis.unibo.it:50000/tw_stud</db-url>
		<db-username>00830325</db-username>
		<db-password>ForzaVale46</db-password>
	</db-instance>
</db>
